apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunilapp
spec:
  selector:
    matchLabels:
      app: sunilapp
  replicas: 6
  template:
    metadata:
      labels:
        app: sunilapp
    spec:
      containers:
      - name: sunilapp
        image: sunildev99/argocd:9
        ports:
        - containerPort: 8080
